#!/usr/bin/env ansible-playbook
- hosts: all
  vars:
    public_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  tasks:
    - name: add public key to authorized_keys
      authorized_key:
        key: "{{ lookup('file', public_ssh_key) }}"
        user: "{{ ansible_env.USER }}"
    - name: transfer bashrc
      copy:
        src: "{{ lookup('env', 'HOME') }}/.bashrc"
        dest: "{{ ansible_env.HOME }}/.bashrc"
    - name: transfer bash_profile
      copy:
        src: "{{ lookup('env', 'HOME') }}/.bash_profile"
        dest: "{{ ansible_env.HOME }}/.bash_profile"
    - name: transfer gitconfig
      copy:
        src: "{{ lookup('env', 'HOME') }}/.gitconfig"
        dest: "{{ ansible_env.HOME }}/.gitconfig"
    - name: transfer gitignore_global
      copy:
        src: "{{ lookup('env', 'HOME') }}/.gitignore_global"
        dest: "{{ ansible_env.HOME }}/.gitignore_global"
    - name: transfer vim directory
      synchronize:
        src: "{{ lookup('env', 'HOME') }}/.vim/"
        dest: "{{ ansible_env.HOME }}/.vim/"
    - name: transfer tmux conf
      synchronize:
        src: "{{ lookup('env', 'HOME') }}/.tmux.conf"
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
